[package]
name = "e_math"
version = "0.1.0"
edition = "2021"
description = "math for babylon"
repository = "https://github.com/moyy/e_babylon"
license = "Apache-2.0"
keywords = ["babylon", "math"]

[dependencies]

[lints]
workspace = true
